function AP = get_AP(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FEMALE1LIN = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  FEMALE1LIN = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Female1lin = importfile("E:\Dropbox (HHMI)\Projects\Unbised\PSD95_EE\Female1_lin.xml", [3, 22]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Jan-2022 20:29:17

%% Input handling

f = strsplit(filename, '_');
filename = [f{1} '_lin.xml'];
% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "=";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "ampoz", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15"];
opts.SelectedVariableNames = "ampoz";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "ampoz", "TrimNonNumeric", true);
opts = setvaropts(opts, "ampoz", "ThousandsSeparator", ",");

% Import the data
AP = readtable(filename, opts);

%% Convert to output type
AP = table2array(AP);
AP = AP(~isnan(AP));
end