function labelsorig = importlabelfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LABELSORIG = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  LABELSORIG = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  labelsorig = importfile("E:\AlignToAllen\VisuAlign-v0_8\ABA_Mouse_CCFv3_2017_25um.cutlas\labels_orig.txt", [16, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Jul-2020 17:48:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [16, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["ID", "R", "G", "B", "A", "Vis", "ID2", "Name"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 8, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 8, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
labelsorig = readtable(filename, opts);

end