function header = makeLabelHeader()
%UNTITLED5 Summary of this function goes here
%   Detailed explanation goes here
header = {'################################################', ...
'# ITK-SnAP Label Description File',...
'# File format:',...
'# IDX   -R-  -G-  -B-  -A--  VIS MSH  LABEL',...
'# Fields:',...
'#    IDX:   Zero-based index',...
'#    -R-:   Red color component (0..255)',...
'#    -G-:   Green color component (0..255)',...
'#    -B-:   Blue color component (0..255)',...
'#    -A-:   Label transparency (0.00 .. 1.00)',...
'#    VIS:   Label visibility (0 or 1)',...
'#    IDX:   Label mesh visibility (0 or 1)',...
'#  LABEL:   Label description',...
'################################################'};
end

