%% clear all
clear; close all;
unbiased_dm11 = 'W:\moharb\Unbiased';
unbiased_dropbox = 'E:\Dropbox (HHMI)\Projects\Unbised\MECP2';
cd(unbiased_dm11)
%%
folders = dir('MECP2*');
folders = {folders.name};
for i = 1:length(folders)
    cd(unbiased_dm11);
    folder = folders{i};
    expression = '\d+$';
    matchStr = regexp(folder,expression,'match');
    ANM = matchStr{1};
    switch ANM
        case '460139'
            times = datetime({...
                '30-Apr-2020 13:50:00',...
                '30-Apr-2020 14:50:00',...
                '30-Apr-2020 15:25:00'})';
            names = {'invivo1','invivo2','exvivo'}';
            dyes = [669,525,585]';
            descriptions = {...
                '200nmol (40/40/100)', ...
                '200nmol (40/40/100)', ...
                '100nmol 50ml 4% PFA'}';
            chs = [3,1,2];
            dye_table = table(names,dyes, chs,descriptions,times,...
                'VariableNames',{'Name','Dye','Ch','Description','DateTime'});
            current = struct('ANM',ANM,'dye_table',dye_table, ...
                'Folder', folder, 'sex', 'M', 'DOB','7/13/19',...
                'z_spaceing', 1200 , 'offset', 1000);
        case '460138'
            times = datetime({...
                '4-May-2020 13:20:00',...
                '4-May-2020 14:25:00',...
                '4-May-2020 15:15:00'})';
            names = {'invivo1','invivo2','exvivo'}';
            dyes = [669,552,608]';
            descriptions = {...
                '200nmol (40/40/100)', ...
                '200nmol (40/40/100)', ...
                '100nmol 50ml 4% PFA'}';
            chs = [3,1,2];
            dye_table = table(names,dyes, chs,descriptions,times,...
                'VariableNames',{'Name','Dye','Ch','Description','DateTime'});
            current = struct('ANM',ANM,'dye_table',dye_table, ...
                'Folder', folder, 'sex', 'M', 'DOB','7/13/19',...
                'z_spaceing', 1200 , 'offset', 1000);
            
        otherwise
            continue
    end
    
    loadOneRoundMECP2(current, unbiased_dm11, unbiased_dropbox);
    
end
